version: "3.0"
services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000/tcp"
      - "9443:9443/tcp"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /opt/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/homeassistant/data:/config
    ports:
      - 8123:8123 #optional
    restart: unless-stopped
    depends_on:
      - mariadb
      - influxdb
      - mosquitto
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883/tcp"
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /opt/mosquitto/config:/mosquitto/config
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/log:/mosquitto/log
    stdin_open: true
    tty: true
  nodered:
    container_name: nodered
    image: nodered/node-red
    restart: unless-stopped
    ports:
      - "1880:1880/tcp"
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /opt/nodered/data:/data
    depends_on:
      - homeassistant
      - mosquitto
